;; Scheme: minimalist Lisp dialect
(let* ((x 2.0)
       (v 3.0)
       (m 5.0)
       (dm_dt 0.1)
       (p (* m v))
       (NKTg1 (* x p))
       (NKTg2 (* dm_dt p)))
  (display "p=") (display p)
  (display " NKTg1=") (display NKTg1)
  (display " NKTg2=") (display NKTg2) (newline))
