name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, node]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python tests
      if: matrix.language == 'python'
      run: |
        if [ -f tests/test.py ]; then python tests/test.py; fi

    - name: Set up Node.js
      if: matrix.language == 'node'
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Node.js dependencies
      if: matrix.language == 'node'
      run: |
        if [ -f package.json ]; then npm install; fi

    - name: Run Node.js tests
      if: matrix.language == 'node'
      run: |
        if [ -f tests/test.js ]; then npm test; fi

